name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Se ejecuta todos los días a medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bryansoberon
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Lima
